### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by christianvari** [Codezen-SRLS/website#1]
The website is still loading the gatsby favicon

![image](https://github.com/user-attachments/assets/24228d61-e4df-475d-9973-5a9738d31b71)

**Comment by MussadiqKhan** [comment]
Please share favicon. I haven't received it yet

**Comment by christianvari** [comment]
You can export it from the design https://www.figma.com/design/VEq21moclWECsJCGOKzhG9/codezensrls-(Dev_link)?node-id=16103-582&m=dev
