### ISSUE TITLE
Page is larger than viewport

### ISSUE THREAD

**Issue by christianvari** [Codezen-SRLS/website#10]
The page is larger than viewport and so the browser shows the bar to scroll horizontally

![image](https://github.com/user-attachments/assets/6db555ca-24ba-494d-9abc-9b0bf275f613)

**Comment by MussadiqKhan** [comment]
@christianvari - I do not see any horizontal scroll. Can you please run gatsby clean and then run the project again on local?

**Comment by christianvari** [comment]
I still can see it, it is because of the last card of the our work section who is a little outside of the viewport
