### ISSUE TITLE
How we work animation has black background on Safari

### ISSUE THREAD

**Issue by christianvari** [Codezen-SRLS/website#5]
The How we work animation has a black background on Safari. It is working correctly on Chrome

<img width="2121" alt="image" src="https://github.com/user-attachments/assets/6408f606-e46d-4454-88d4-018c41a7bf7e">

**Comment by MussadiqKhan** [comment]
Looks fine on safari
![Uploading Screenshot 2024-10-11 at 5.14.43 PM.png…]()

**Comment by MussadiqKhan** [comment]
<img width="1438" alt="Screenshot 2024-10-11 at 5 14 43 PM" src="https://github.com/user-attachments/assets/c757ad8a-9bb0-4bae-8d13-dee0aeeb7ad1">
