### ISSUE TITLE
[Mobile] No carousel for "our work" section

### ISSUE THREAD

**Issue by christianvari** [Codezen-SRLS/website#9]
In mobile, the "our work" section does not have a carousel. It should work as in the desktop version but sliding horizontally.
So having 1 column with 3 rows and slides horizontally by showing another column with 3 rows

**Comment by MussadiqKhan** [comment]
@christianvari There's no carousel in figma as well. They are all stacked on top of each other.

**Comment by christianvari** [comment]
You're correct @MussadiqKhan . Can you still make this modification?

**Comment by MussadiqKhan** [comment]
@christianvari - This is not how carousel works. Having three items in a column means user will skip items as all 3 items may not be in the viewport. It can have 1 item at a time.

**Comment by christianvari** [comment]
Ok, let's close this for now
